# docker-compose.yaml
services:
  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web/static:/static
    links:
      - app:app
    networks:
      - frontnet

  app:
    restart: always
    build: ./app
    container_name: app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USE_SSL: ${MAIL_USE_SSL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    volumes:
      - ./app/data:/app/web/data
    expose:
      - "80:8000"
    networks:
      - frontnet
      - backnet
    depends_on:
      - postgres
    command: >
      sh -c "python3 ./create_db.py &&
             gunicorn -w 2 -b :8000 app:app"

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - backnet

networks:
  frontnet:
  backnet:

volumes:
  db-data:
