# docker-compose.yaml
version: '3'

services:
  h3o-inferno:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    command: ["python3", "app.py"]
    ports:
      - "1025:1025"
    volumes:
      - ./src/data:/app/src/data
    env_file:
      - ./.env

