# docker-compose.yaml
services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    command: ["python3", "app.py"]
    ports:
      - "1025:1025"
    volumes:
      - ./web/data:/app/web/data
    env_file:
      - ./.env

